config/routes.rb
Jamsession::Application.routes.draw do

  
  resources :styles
  resources :skills

  resources :spaces do 
    member do 
      post 'post_review'
    end
    collection do
      get 'search'
    end
  end

  devise_for :users
  resources :users do
    collection do 
      get 'search'
    end
  end

  resources :messages do
    member do 
      post 'reply'
      post 'mark'
    end
    collection do
      get 'inbox'
      get 'sent'
      post 'send_message'
    end
  end

  

  root :to => 'welcome#index'

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!

  def all
    @messages = current_user.messages
                            .paginate(page: params[:page], per_page: 10)
  end

  def inbox
    @messages = current_user.received_messages
                            .paginate(page: params[:page], per_page: 10)
  end

  def sent
    @messages = current_user.sent_messages
                            .paginate(page: params[:page], per_page: 10)
  end 

  def show
    @message = current_user.messages.with_id(params[:id])
  end

  def destroy
    @message = current_user.messages.with_id(params[:id]).first
    if @message.destroy
      flash[:notice] = "All ok"
    else
      flash[:error] = "Fail"
    end
  end

  def reply
    message = current_user.received_messages.find(params[:id])
    message.reply(topic: params[:subject], body: params[:body])
    redirect_to :back, notice: "Reply sent to #{message.to.name}"
  end

  def send_message
    from = current_user
    to = User.find(params[:id])
    from.send_message(to, params[:subject], params[:body])
    respond_to do |format|
      format.html { redirect_to inbox_messages_path, 
                                 notice: "Message sent to #{to.name}"}
      format.js { render json: "sent".to_json if request.xhr? }
    end
  end

  def mark
    message = current_user.received_messages.find(params[:id])
      message.mark_as_read
    redirect_to :back
  end

end

#https://github.com/LTe/acts-as-messageable 

app/helpers/messages_helper.rb
module MessagesHelper
  def other_guy(message)
      user = message.from == current_user ? message.to : message.from
  end

  def other_guys_picture(message)
      other_guy(message).profile_picture.url(:thumb)
  end

  def new_tag(message)
    if message.to == current_user and not message.opened?
      styles = %w{badge badge-info}
      mark = link_to("Mark As Read", mark_message_path(message), method: :post)
      inside = content_tag(:span, 'New', class:styles)
      content_tag(:div, inside + mark, class:'status')
    end
  end
end

app/views/messages/_message.html.erb
<div class="message" >
  <div class="inside">
    <div class="picture"><%= image_tag other_guys_picture message %></div>
    <%= new_tag message %>
    <div class="name">From: <%= link_to message.from.name, message.from %></div>
    <div class="name">To: <%= link_to message.to.name, message.to%></div>
    <div class="sent">Sent <%= time_ago_in_words message.created_at %> ago</div>
    <div class="topic"><%= message.topic %></div>
    <div class="body"><%= message.body %></div>
  </div>

  <div class="reply-side">
    <div class="btn btn-primary reply-btn">Reply</div>
    <div class="reply">
      <% if message.to == current_user %>
        <form action="<%=reply_message_path(message)%>" method="POST" class="reply-form">
      <% else %>
        <form action="<%=send_message_messages_path %>" method="POST" class="reply-form">
        <input name="id" value="<%= message.to.id %>" type="hidden" />
      <% end %>
        <input name="subject" value="<%= message.topic %>" type="hidden" />
        <textarea id="reply" name="body"></textarea>
        <br />
        <input type="submit" value="Reply" />
        <%= token_tag(nil) %>
      </form>
    </div>
  </div>

<hr />
</div>

app/views/messages/all.html.erb
<div class="sent-mail-header">
  <h1>All Messages</h1>
  <%= link_to "See Inbox", inbox_messages_path  %>
  <br />
  <%= link_to "See Sent Messages", sent_messages_path  %>
</div>
<% if @messages.empty? %>
  <h2>No messages</h2>
<% else %>
  <%= render partial: 'message', collection: @messages %>
  <%= will_paginate @messages %>
<% end %>

app/views/messages/inbox.html.erb
<div class="sent-mail-header">
  <h1>Inbox</h1>
  <%= link_to "See Sent Messages", sent_messages_path  %>
</div>
<% if @messages.empty? %>
  <h2>No new messages</h2>
<% else %>
  <%= render partial: 'message', collection: @messages %>
  <%= will_paginate @messages %>
<% end %>

app/views/messages/sent.html.erb
<div class="sent-mail-header">
  <h1>Sent Messages</h1>
  <%= link_to "See Inbox", inbox_messages_path  %>
</div>
<% if @messages.empty? %>
  <h2>No sent messages</h2>
<% else %>
  <%= render partial: 'message', collection: @messages %>
<% end %>