config/routes.rb
Jamsession::Application.routes.draw do

  
  resources :styles
  resources :skills

  resources :spaces do 
    member do 
      post 'post_review'
    end
    collection do
      get 'search'
    end
  end

  devise_for :users
  resources :users do
    collection do 
      get 'search'
    end
  end

  resources :messages do
    member do 
      post 'reply'
      post 'mark'
    end
    collection do
      get 'inbox'
      get 'sent'
      post 'send_message'
    end
  end

  

  root :to => 'welcome#index'

end

app/models/space.rb
class Space < ActiveRecord::Base
  attr_accessible :about, :availability, :capacity, :description, :equipment, :hourly_pricing, :location, :name, :rooms, :size
  has_attached_file :profile_picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  attr_accessible :profile_picture
  has_many :reviews

  geocoded_by :location
  after_validation :geocode

  scope :by_max_price, (lambda do |price|
    Space.where('hourly_pricing <= ?', price) unless price.nil?
  end)

  scope :by_services, (lambda do |services|
    Space.where(services: services) unless services.nil? or services.empty?
  end)

  scope :by_min_people, (lambda do |minimum|
    Space.where('space.capacity < num_people') unless minimum.nil?
  end)

end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :search]
  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spaces }
    end
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
    @space = Space.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @space }
    end
  end

  # GET /spaces/new
  # GET /spaces/new.json
  def new
    @space = Space.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @space }
    end
  end

  # GET /spaces/1/edit
  def edit
    @space = Space.find(params[:id])
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(params[:space])

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render json: @space, status: :created, location: @space }
      else
        format.html { render action: "new" }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spaces/1
  # PUT /spaces/1.json
  def update
    @space = Space.find(params[:id])
    
    respond_to do |format|
      if @space.update_attributes(params[:space])
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space = Space.find(params[:id])

    @space.destroy

    respond_to do |format|
      format.html { redirect_to spaces_url }
      format.json { head :no_content }
    end
  end

  def search 
    @price_limit = params[:price_limit] || nil
    @min_people = params[:min_people] || nil
    @services = params[:services] || []

    @location = params[:location] || request.location

    if Rails.env.development? and !params[:location]
      @location = "NYC"
    end

    @miles = params[:miles] || 20
    @spaces = Space.paginate(page: params[:page], per_page: 25).
                  near(@location, @miles).
                  by_max_price(@price_limit).
                  by_services(@services).
                  by_min_people(@min_people).
                  all
  end

  def post_review
    @space = Space.find(params[:id])
    review = Review.new(params[:review])
    review.posted_by = current_user
    review.belongs_to(space)
    respond_to do |format|
      if review.save
        format.html { redirect_to @space, notice: 'Review was successfully created.' }
        format.json { render json: @space, status: :created, location: @space }
      else
        format.html { render action: "get" }
        format.json { render json: review.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :hourly_pricing %><br />
    <%= f.text_field :hourly_pricing %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :availability %><br />
    <%= f.text_field :availability %>
  </div>
  <div class="field">
    <%= f.label :equipment %><br />
    <%= f.text_field :equipment %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.text_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :rooms %><br />
    <%= f.text_field :rooms %>
  </div>
  <div class="field">
    <%= f.label :about %><br />
    <%= f.text_area :about %>
  </div>
  <div class="field">
    <%= f.label :profile_picture %><br />
    <%= f.file_field :profile_picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spaces/_space.html.erb
<div class="space">
  <span class="profile_picture">
    <%= image_tag space.profile_picture %>
  </span>
  <div class="name">
    <%= space.name %>
  </div>
  <div class="location">
    <%= space.location %>
  </div>
  <div class="price">
    <%= number_to_currency space.hourly_pricing %>
  </div>
</div>

app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<h1>Listing spaces</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Hourly pricing</th>
    <th>Description</th>
    <th>Availability</th>
    <th>Equipment</th>
    <th>Capacity</th>
    <th>Size</th>
    <th>Rooms</th>
    <th>About</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spaces.each do |space| %>
  <tr>
    <td><%= space.name %></td>
    <td><%= space.location %></td>
    <td><%= space.hourly_pricing %></td>
    <td><%= space.description %></td>
    <td><%= space.availability %></td>
    <td><%= space.equipment %></td>
    <td><%= space.capacity %></td>
    <td><%= space.size %></td>
    <td><%= space.rooms %></td>
    <td><%= space.about %></td>
    <td><%= link_to 'Show', space %></td>
    <td><%= link_to 'Edit', edit_space_path(space) %></td>
    <td><%= link_to 'Destroy', space, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Space', new_space_path %>

app/views/spaces/new.html.erb
<h1>New space</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/search.html.erb
<div class="row">
  <div class="span3" id="filter">
    <div class="filter">Filter</div>
    <%= form_tag(search_users_path, method: :get, class: 'form-vertical') do %>
      <%= label_tag :location, "Location" %>
      <%= search_field_tag :location, @location,  placeholder: 'Enter Zip or City' %>


      <br />

      <%= label_tag :services, "Services" %>
      <% ['rehearsal', 'recording', 'mastering', 'production'].each do |service| %>
        <%= check_box_tag 'services[]', 
            service, @services.include?(service), 
            id: "service_#{service}" %>
        <%= label_tag "services_#{service}", service.humanize %>
        <br />
      <% end %>

      <%= submit_tag "Filter"%>
    <% end %>
  </div>

<div class="span9">
  <%= map_tag @location, @spaces %>

  <div class="spaces">
    <%= render @spaces %>
  </div>

  <%= will_paginate @spaces %>
</div>

app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @space.name %>
</p>

<p>
  <b>Location:</b>
  <%= @space.location %>
  <br />
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@space.latitude}%2C#{@space.longitude}" %>
</p>

<p>
  <b>Hourly pricing:</b>
  <%= @space.hourly_pricing %>
</p>

<p>
  <b>Description:</b>
  <%= @space.description %>
</p>

<p>
  <b>Availability:</b>
  <%= @space.availability %>
</p>

<p>
  <b>Equipment:</b>
  <%= @space.equipment %>
</p>

<p>
  <b>Capacity:</b>
  <%= @space.capacity %>
</p>

<p>
  <b>Size:</b>
  <%= @space.size %>
</p>

<p>
  <b>Rooms:</b>
  <%= @space.rooms %>
</p>

<p>
  <b>About:</b>
  <%= @space.about %>
</p>

<%= image_tag @space.profile_picture.url %>


<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>