config/routes.rb
Jamsession::Application.routes.draw do

  
  resources :styles
  resources :skills

  resources :spaces do 
    member do 
      post 'post_review'
    end
    collection do
      get 'search'
    end
  end

  devise_for :users
  resources :users do
    collection do 
      get 'search'
    end
  end

  resources :messages do
    member do 
      post 'reply'
      post 'mark'
    end
    collection do
      get 'inbox'
      get 'sent'
      post 'send_message'
    end
  end

  

  root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :location, :hide_location_from_search, :about
  attr_accessible  :profile_picture

  validates_presence_of :name
  
  has_many :personal_skills
  has_many :personal_styles
  has_many :skills, through: :personal_skills, dependent: :destroy
  has_many :styles, through: :personal_styles, dependent: :destroy
  
  accepts_nested_attributes_for :personal_skills
  accepts_nested_attributes_for :personal_styles

  acts_as_messageable
  geocoded_by :location
  has_attached_file :profile_picture, 
                    styles: { :medium => "300x300>", :thumb => "100x100>" }

  before_save :clear_location
  after_validation :geocode

  default_scope where(hide_location_from_search: false)

  def self.by_skills(skills)
    if skills.nil? or skills.empty?
      scoped
    else
      joins(:skills).
      where('skills.name'=> skills).
      group("users.id").
      having("COUNT(skills.id) >= ?", skills.length)
    end
  end

  def self.by_styles(styles)
    if styles.nil? or styles.empty?
      scoped
    else
      joins(:styles).
      where('styles.name'=> styles).
      group("users.id").
      having("COUNT(styles.id) >= ?", styles.length)
    end
  end


  def clear_location 
    if self.hide_location_from_search
      self.latitude = nil
      self.longitude = nil
    end
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :search]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /user/1/edit
  def edit
    @user = current_user
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = current_user

    # XXX optimize later, because this is retarded (excuse: demo-day)

    # splits out style/skills for regeneration 
    user_params = params[:user].except(:styles).except(:skills)
    rest = params[:user].slice(:styles, :skills)

    # update skills/styles by destroying all and regenerating them
    @user.styles.destroy_all
    @user.skills.destroy_all

    updated = @user.update_attributes(user_params)
    if updated 
      styles_param = params[:user][:styles]
      if styles_param
        styles_param.split(',').each do |style_id|
          ps = PersonalStyle.create(style: Style.find_by_id(style_id),
                                    user: @user)
        end
      end
      if
        skills_param = params[:user][:skills]
        skills_param.split(',').each do |skill_id|
          ps = PersonalSkill.create(skill: Skill.find_by_id(skill_id),
                                    user: @user,
                                    expertise_level: 2)
        end
      end
    end

    respond_to do |format|
      if updated
        format.html { redirect_to @user, notice: 'Space was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def search 
    @skills = params[:skills].to_s.split(',')
    @styles = params[:styles].to_s.split(',')

    @location = params[:location] || request.location
    if Rails.env.development? and !params[:location]
      @location = "NYC"
    end

    @miles = params[:miles] || 20

    @users = User.near(@location, @miles)
                 .by_skills(@skills)
                 .by_styles(@styles)
                 .paginate(page: params[:page], per_page: 25)


    # clean up for javascript tags
    @skills = @skills.map { |name| Skill.find_by_name(name) }
    @styles = @styles.map { |name| Style.find_by_name(name) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_needs_more_info
    if user_signed_in?
      user = current_user
      if user.location.nil? or user.nil?
        content_tag :div, "Need more information in profile!", class: "need_more"
      end
    end
  end
  def map_tag_for_user(user)
    tag 'img', alt:"User", src: "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{user.latitude}%2C#{user.longitude}" unless user.latitude.nil? 
  end
end

app/views/users/_form.html.erb
<div id="edit-user">
<%= simple_form_for(@user, html: {class: 'form-horizontal' }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :about, as: :text %>
  <%= image_tag current_user.profile_picture(:thumb) %>
  <%= f.input :profile_picture, as: :file %>

  <div class="style">
    <%= f.label :styles %> <br />
    <%= f.text_field :styles, id: 'search-styles', value: token_input(@user.styles) %>
  </div>
  <div class="skill">
    <%= f.label :skills %> <br />
    <%= f.text_field :skills, placeholder:"",  id: 'search-skills', value: token_input(@user.skills) %>
  </div>

  <br />
  
  <%= f.input :hide_location_from_search, as: :boolean,
              label: 'Hide Location and Availability From Search Listings' %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/users/_user.html.erb
<div class="user">
  <div class="map-letter"> <%= iToAZ user_counter %></div>
  <input id="user-<%= user.id %>" class="hidden-id" type="hidden" value="<%= user.id %>" />
  <span class="profile_picture">
    <% unless user.profile_picture.nil? %>
      <%= image_tag user.profile_picture.url(:thumb) %>
    <% end %>
  </span>
  <div class="contact">
    <form action="<%= send_message_messages_path(user) %>" method="post">
      <%= image_tag 'contact.png' %>
    </form>
  </div>
  <div class="information">
    <div class="name">
      <%= link_to user.name, user %>
    </div>
    <div class="location">
      <%= user.location %>
    </div>
    <div class="skills">
     <p>Skills: <%= user.skills.map(&:name).join(", ") %> </p>
    </div>
    <div class="styles">
     <p>
     Styles: <%= user.styles.map(&:name).join(', ') %>
     </p>
    </div>
  </div>

  <div class="message"></div>
  <hr />
</div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.name %></td>
    <td><%= user.location %></td>
    <td><%= link_to 'Show', user %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>

app/views/users/search.html.erb
<div class="row-fluid">
  <div class="span3" id="filter">
    <div class="filter">Filter</div>
    <%= form_tag(search_users_path, method: :get, class: 'form-vertical') do %>
      <%= label_tag :location, "Location" %>
      <%= search_field_tag :location, @location,  placeholder: 'Enter Zip or City' %>
      <p>
      <%= label_tag :styles, "Styles" %> <br />
      <%= text_field_tag :styles, "",  id: 'search-styles', value: token_input(@styles) %>
      </p>
      <p>
      <%= label_tag :skills, "Skills" %> <br />
      <%= text_field_tag :skills, "", placeholder:"e.g. Guitar, Drums, Vocals",
                          id: 'search-skills', value: token_input(@skills) %>
      </p>

      <br />
      <div id="filter-btn">
        <%= submit_tag "Filter", class: "btn btn-primary btn-large"%>
      </div>
    <% end %>
  </div>
  <div class="span6">
  <%= map_tag @location, @users %>
  
  <div class="users">
    <%= render(@users) || "Nobody found. Try readjusting your search parameters and try again." %>
  </div>

  <%= will_paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<div id="show">
<div class="row-fluid">
  <div class="span6">

    <div class="name">
      <%= @user.name %>
      <% if current_user == @user %>
        <br />
        <%= link_to 'Edit Profile', edit_user_path(@user) %> 
      <% end %>
    </div>

    <div class="profile_picture">
      <% unless @user.profile_picture.nil? %>
        <%= image_tag @user.profile_picture.url(:medium) %>
      <% end %>
    </div>


    <div class="skills">
     <p><b>Skills:</b> <%= @user.skills.map(&:name).join(", ") %> </p>
    </div>
    <div class="styles">
     <p>
     <b>Styles:</b> <%= @user.styles.map(&:name).join(', ') %>
     </p>
    </div>


    <p>
      <b>About:</b>
      <%= @user.about %>
    </p>
    <p>
  </div>

  
    <div class="span6">
      <b>Location:</b>
      <%= @user.location %>
      <br />
        <%= map_tag_for_user(@user) %>
    </div>
</div>
</div>