config/routes.rb
Jamsession::Application.routes.draw do

  
  resources :styles
  resources :skills

  resources :spaces do 
    member do 
      post 'post_review'
    end
    collection do
      get 'search'
    end
  end

  devise_for :users
  resources :users do
    collection do 
      get 'search'
    end
  end

  resources :messages do
    member do 
      post 'reply'
      post 'mark'
    end
    collection do
      get 'inbox'
      get 'sent'
      post 'send_message'
    end
  end

  

  root :to => 'welcome#index'

end

app/models/style.rb
class Style < ActiveRecord::Base
  attr_accessible :name

  validates_presence_of :name

  has_many :personal_styles
  has_many :users, through: :personal_styles
  
  before_create :normalize_name

  def normalize_name
    self.name = self.name.titleize.strip
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController

  def new
    @style = Style.new
  end

  def create
    @style = Style.new(params[:style])
    if @style.save
      redirect_to @style, notice: "Style was created successfully."
    else 
      render action: "new"
    end
  end

  def edit
    @style = Style.find(params[:id])
  end

  def update
    @style = Style.find(params[:id])
    @style.update_attributes(params[:style])
  end

  def show
    @style = Style.find(params[:id])
  end

  def index
    if params[:q]
      #FIXME SQL INJECTION RISK
      @styles = Style.where("upper(name) LIKE upper('%#{params[:q]}%')")
    else
      @styles = Style.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @styles }
    end
  end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/_style.html.erb
<%= style.name %>
<br />

app/views/styles/index.html.erb
<%= render(@styles) || "There are no styles" %>

<br />

<%= link_to 'New Style', new_style_path %>

app/views/styles/new.html.erb
<h1>New Style</h1>

<%= render 'form' %>

<%= link_to 'Back', styles_path %>

app/views/styles/show.html.erb
<%= @style.name %>